apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pihole-dns
  namespace: metallb
spec:
  addresses:
  - CIDR
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pihole-dns
  namespace: metallb
spec:
  ipAddressPools:
  - pihole-dns