apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pihole
  namespace: pihole
spec:
  provider: vault
  parameters: # Vault Parameters
    roleName: "pihole"
    vaultCACertPath: "/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    objects: |
      - objectName: "pihole-admin-password"
        secretPath: "op/vaults/VAULT_ID/items/pihole"
        secretKey: "password"
  secretObjects: # Will become the secret with the following
  - secretName: pihole-admin-password
    type: Opaque
    data:
    - objectName: pihole-admin-password
      key: password