#!/usr/bin/env bash
set -euo pipefail




# ----------------------------
# DEPENDENCY CHECKS
# ----------------------------
command -v mc >/dev/null 2>&1 || { echo >&2 "Error: 'mc' is not installed. Install MinIO client first."; exit 1; }
command -v vault >/dev/null 2>&1 || { echo >&2 "Error: 'vault' is not installed. Install HashiCorp Vault CLI first."; exit 1; }

# ----------------------------
# ENV CHECK
# ----------------------------
: "${VAULT_ADDR:?Error: VAULT_ADDR is not set. Set it to your Vault server address.}"
: "${VAULT_TOKEN:?Error: VAULT_TOKEN is not set. Export your Vault token.}"
: "${MINIO_ENDPOINT:?Error: MINIO_ENDPOINT is not set. Please set with protocol.}"
: "${MINIO_USER:?Error: MINIO_USER is not set. Please set configure user with admin rights.}"
: "${MINIO_PASSWORD:?Error: MINIO_PASSWORD is not set. Please set configure user with admin rights.}"

# ----------------------------
# ARGS Check
# ----------------------------
CREDENTIAL_NAME="${1:?Usage: $0 <credential_name> <vault_path>}"
VAULT_PATH="${2:?Usage: $0 <credential_name> <vault_path>}"

# Test Vault connection
if ! vault status >/dev/null 2>&1; then
  echo "Error: Cannot connect to Vault at $VAULT_ADDR. Check VAULT_ADDR and network."
  exit 1
fi

MINIO_ALIAS="myminio"

# Temporary file
TEMP_FILE=$(mktemp)
TEMP_SECRET=$(mktemp)

# ----------------------------
# STEP 1: Configure mc alias
# ----------------------------
echo "Configuring mc alias..."
mc alias set $MINIO_ALIAS "https://$MINIO_ENDPOINT" "$MINIO_USER" "$MINIO_PASSWORD"

# ----------------------------
# STEP 2: Create service account
# ----------------------------
echo "Creating service account..."
mc admin user svcacct add $MINIO_ALIAS "$CREDENTIAL_NAME" > "$TEMP_FILE"

ACCESS_KEY=$(grep '^Access Key:' "$TEMP_FILE" | awk '{print $3}')
SECRET_KEY=$(grep '^Secret Key:' "$TEMP_FILE" | awk '{print $3}')


# Only login, password and database category supoprted
cat > "$TEMP_SECRET" <<EOF
{
  "category": "login",
  "title": "$CREDENTIAL_NAME",
  "tags": ["$CREDENTIAL_NAME", "credentials", "server", "autogenerated"],
  "fields": [
    {
      "id": "username",
      "label": "username",
      "type": "STRING",
      "purpose": "USERNAME",
      "value": "$ACCESS_KEY"
    },
    {
      "id": "password",
      "label": "password",
      "purpose": "PASSWORD",
      "type": "CONCEALED",
      "value": "$SECRET_KEY"
    },
    {
      "id": "notesPlain",
      "type": "STRING",
      "purpose": "NOTES",
      "label": "notesPlain",
      "value": "[default]\naws_access_key_id=$ACCESS_KEY\naws_secret_access_key=$SECRET_KEY"
    }
  ]
}
EOF

# ----------------------------
# STEP 4: Store credentials in Vault
# ----------------------------
echo "Storing credentials in Vault at $VAULT_PATH..."
vault write "$VAULT_PATH" @"$TEMP_SECRET"

# ----------------------------
# STEP 5: Cleanup
# ----------------------------
echo "Cleaning up temporary file..."
shred -u "$TEMP_FILE" "$TEMP_SECRET"

echo "Done. Velero credentials are safely in Vault."