apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: persistent
  labels: {
    component: "storage",
    part-of: "truenas"
  }
provisioner: nfs.csi.k8s.io
parameters:
  server: SERVER
  share: SHARE
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
  annotations: {
    storageclass.kubernetes.io/is-default-class: "true"
  }
  labels: {
    component: "storage",
    part-of: "truenas"
  }
provisioner: nfs.csi.k8s.io
parameters:
  server: SERVER
  share: SHARE
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true