podLabels:
  component: argocd
  part-of: cd
redis-ha:
  enabled: true
server:
  autoscaling:
    enabled: true
    minReplicas: 2
repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
applicationSet:
  replicas: 2