variable "priority_class" {
  description = "Describe the priority class pods should be in"
  type        = string
  default     = null
}

variable "enable_metrics" {
  description = "Whether to enable metrics"
  type        = bool
  default     = false
}

# -----------------------------------------------------------------------------
# Istio Gateway
# -----------------------------------------------------------------------------
variable "istio_chart_version" {
  description = "Istio Chart Version"
  default     = "1.30.2"
}

variable "gateway_crds_version" {
  description = "Gateway API CRDs Version"
  default     = "v1.6.0"
}

variable "istio_ip" {
  description = "Load Balancer IP assigned for Istio"
  type        = string
}

variable "gateway_certificates" {
  description = "List of certificates for the gateway to be generated by cert-manager. For each cert an HTTPS Listener will be created"
  type = list(object({
    hostname       = string
    cluster_issuer = string
  }))
}

variable "tcp_routes" {
  type = list(object({
    name      = string
    port      = number
    namespace = optional(string)
  }))
  default = []
}

# -----------------------------------------------------------------------------
# Resources Variables
# -----------------------------------------------------------------------------

variable "istiod_resources_requests_cpu" {
  type    = string
  default = "50m"
}

variable "istiod_resources_requests_memory" {
  type    = string
  default = "128Mi"
}

variable "istiod_resources_limits_cpu" {
  type    = string
  default = "200m"
}

variable "istiod_resources_limits_memory" {
  type    = string
  default = "256Mi"
}

# istio-ingressgateway
variable "gateway_resources_requests_cpu" {
  type    = string
  default = "50m"
}

variable "gateway_resources_requests_memory" {
  type    = string
  default = "64Mi"
}

variable "gateway_resources_limits_cpu" {
  type    = string
  default = "200m"
}

variable "gateway_resources_limits_memory" {
  type    = string
  default = "256Mi"
}

# -----------------------------------------------------------------------------
# Metallb
# -----------------------------------------------------------------------------

variable "metallb_chart_version" {
  description = "Metal LB Chart Version"
  default     = "0.16.1"
}

variable "uses_metallb" {
  description = "Uses metallb to provide IPs to the controller"
  default     = false
}

variable "prometheus_service_account" {
  description = "Service account used by Prometheus, required for MetalLB's rbacPrometheus scrape RBAC"
  type        = string
  default     = "prometheus-stack-kube-prom-prometheus"
}

variable "prometheus_namespace" {
  description = "Namespace Prometheus runs in, required for MetalLB's rbacPrometheus scrape RBAC"
  type        = string
  default     = "prometheus-stack"
}

# =============================================================================
# Resource Variables
# =============================================================================

variable "controller_memory_request" {
  type    = string
  default = "50Mi"
}

variable "controller_memory_limit" {
  type    = string
  default = "150Mi"
}

variable "controller_cpu_request" {
  type    = string
  default = "50m"
}

variable "controller_cpu_limit" {
  type    = string
  default = "100m"
}

variable "speaker_memory_request" {
  type    = string
  default = "150Mi"
}

variable "speaker_memory_limit" {
  type    = string
  default = "400Mi"
}

variable "speaker_cpu_request" {
  type    = string
  default = "50m"
}

variable "speaker_cpu_limit" {
  type    = string
  default = "100m"
}
